/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * CODE_DUEL API
 * CODE_DUELのAPI仕様書です。
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import useSwr from 'swr'
import type {
  Key,
  SWRConfiguration
} from 'swr'
import type {
  Deck
} from '../index.schemas'


  
  /**
 * デッキ一覧を取得する
 * @summary デッキ一覧を取得する
 */
export const getDecks = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Deck[]>> => {
    return axios.get(
      `/deck`,options
    );
  }



export const getGetDecksKey = () => [`/deck`] as const;


export type GetDecksQueryResult = NonNullable<Awaited<ReturnType<typeof getDecks>>>
export type GetDecksQueryError = AxiosError<unknown>

/**
 * @summary デッキ一覧を取得する
 */
export const useGetDecks = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDecks>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDecksKey() : null);
  const swrFn = () => getDecks(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, {
    
    ...swrOptions
  })

  return {
    swrKey,
    ...query
  }
}
