openapi: "3.0.0"
info:
  version: "1.0"
  title: CODE_DUEL API
  description: CODE_DUELのAPI仕様書です。
paths:
  /signUp:
    post:
      tags:
        - user
      summary: ユーザー登録
      description: ユーザーの登録を行う。初回アクセス時のみフロントからリクエストが送られる。
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
  /signIn:
    post:
      tags:
        - user
      summary: ユーザーログイン
      description: ログインを行う。ブラウザにidが保存されている場合にリクエストが送られる。
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                user_name:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
  /deck:
    get:
      tags:
        - decks
      summary: デッキ一覧を取得する
      description: デッキ一覧を取得する
      operationId: getDecks
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/deck"
  /cards:
    get:
      tags:
        - cards
      summary: カード一覧を取得する
      description: カード一覧を取得する
      operationId: getCards
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/card"
  /cards/{id}:
    get:
      tags:
        - cards
      summary: カードを取得する
      description: カードを取得する
      operationId: getCard
      parameters:
        - name: id
          in: path
          description: カードのID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/card"
  /combo:
    get:
      tags:
        - combos
      summary: コンボを取得する
      description: コンボを取得する
      operationId: getCombo
      parameters:
        - name: cards
          in: query
          description: カードのID
          required: true
          schema:
            type: array
            items:
              type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/combo"

components:
  schemas:
    user:
      title: user
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        rate:
          type: integer
      required:
        - id
        - name
        - rate
    deck:
      title: deck
      type: object
      properties:
        name:
          type: string
        cards:
          type: array
          items:
            $ref: "#/components/schemas/card"
      required:
        - name
        - cards
    card:
      title: card
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        value:
          type: integer
        type:
          type: string
          enum: [attack, heal, absorption]
        image_src:
          type: string
      required:
        - id
        - name
        - value
        - type
        - image_src
    cards:
      title: cards
      type: array
      items:
        $ref: "#/components/schemas/card"
    combo:
      title: combo
      type: object
      properties:
        name:
          type: string
        cards:
          type: array
          items:
            $ref: "#/components/schemas/card"
        type:
          type: string
          enum: [attack, heal, absorption]
        value:
          type: integer
      required:
        - name
        - cards
        - type
        - value
