"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    const now = new Date();
    return queryInterface.bulkInsert(
      "Cards",
      [
        {
          name: "actix_web",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "actix_web.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Angular",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Angular.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "ASP.NET Core",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "ASP.NET Core.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Bootstrap",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Bootstrap.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "C",
          value: 40,
          type: "attack",
          cost: 4,
          osId: 1,
          filePath: "C.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "C#",
          value: 50,
          type: "attack",
          cost: 5,
          osId: 1,
          filePath: "C#.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "C++",
          value: 50,
          type: "attack",
          cost: 5,
          osId: 1,
          filePath: "C++.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "cakePHP",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "cakePHP.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "cobol",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "cobol.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "CSS",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "css.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "dart",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "dart.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Django",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "django.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Echo",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Echo.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Electron",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Elixir.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Elixir",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Elixir.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "FastAPI",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "FastAPI.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Flask",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Flask.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Flutter",
          value: 30,
          type: "attack",
          cost: 3,
          osId: 1,
          filePath: "Flutter.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Fortran",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Fortran.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Gatby",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Gatsby.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Go",
          value: 40,
          type: "attack",
          cost: 4,
          osId: 1,
          filePath: "Go.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Haskell",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Haskell.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "HTML",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "HTML.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Java",
          value: 50,
          type: "attack",
          cost: 5,
          osId: 1,
          filePath: "Java.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "JavaScript",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "JavaScript.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "JQuery",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "JQuery.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Julia",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Julia.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Kotlin",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Kotlin.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Ktor",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Ktor.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Laravel",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Laravel.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "MaterialUI",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "MaterialUI.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "matlab",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "matlab.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Next.js",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Next.js.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Node.js",
          value: 30,
          type: "attack",
          cost: 3,
          osId: 1,
          filePath: "Node.js.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Nuxt.js",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Nuxt.js.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Objective-C",
          value: 30,
          type: "attack",
          cost: 3,
          osId: 1,
          filePath: "Objective-C.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Perl",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Perl.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "phoenix",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "phoenix.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "PHP",
          value: 30,
          type: "attack",
          cost: 3,
          osId: 1,
          filePath: "PHP.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Python",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Python.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "R",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "R.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "React",
          value: 30,
          type: "attack",
          cost: 3,
          osId: 1,
          filePath: "React.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Ruby",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Ruby.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Rust",
          value: 40,
          type: "attack",
          cost: 4,
          osId: 1,
          filePath: "Rust.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Sass",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Sass.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Scala",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Scala.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Scratch",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Scratch.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Spring",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Spring.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "SQL",
          value: 40,
          type: "attack",
          cost: 4,
          osId: 1,
          filePath: "SQL.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Svelte",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Svelte.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Swift",
          value: 30,
          type: "attack",
          cost: 3,
          osId: 1,
          filePath: "Swift.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "SwiftUI",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "SwiftUI.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "tailwind",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "tailwind.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "tauri",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "tauri.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "TypeScript",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "TypeScript.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Vue.js",
          value: 20,
          type: "attack",
          cost: 2,
          osId: 1,
          filePath: "Vue.js.png",
          createdAt: now,
          updatedAt: now,
        },
        {
          name: "Vuetify",
          value: 10,
          type: "attack",
          cost: 1,
          osId: 1,
          filePath: "Vuetify.png",
          createdAt: now,
          updatedAt: now,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    return await queryInterface.bulkDelete("Cards", null, {});
  },
};
